### ISSUE TITLE
Unable to install with composer

### ISSUE THREAD

**Issue by shiquemano** [mervick/aes-everywhere#15]
I am trying to install this library and I am getting the following output and failure.  Am I doing something wrong?

$ composer require mervick/aes-everywhere -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/pki/tls/certs/ca-bundle.crt: valid
Executing command (/home/foo): git branch --no-color --no-abbrev -v
Reading /home/foo/vendor/composer/installed.json
Running 1.5.1 (2017-08-09 16:07:22) with PHP 5.6.40 on Linux / 4.14.121-85.96.amzn1.x86_64
Downloading https://packagist.org/packages.json
Writing /home/foo/.composer/cache/repo/https---packagist.org/packages.json into cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-2015.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-2016.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-2017.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-2018.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-2018-10.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-2019-01.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-2019-04.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-2019-07.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/p-provider-latest.json from cache
Reading /home/foo/.composer/cache/repo/https---packagist.org/provider-mervick$aes-everywhere.json from cache

                                                                                                                     
  [InvalidArgumentException]                                                                                         
  Could not find package mervick/aes-everywhere at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability                                                                              
                                                                                                                     

Exception trace:
 () at phar:///usr/bin/composer/src/Composer/Command/InitCommand.php:647
 Composer\Command\InitCommand->findBestVersionForPackage() at phar:///usr/bin/composer/src/Composer/Command/InitCommand.php:369
 Composer\Command\InitCommand->determineRequirements() at phar:///usr/bin/composer/src/Composer/Command/RequireCommand.php:117
 Composer\Command\RequireCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:861
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:208
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:54
 require() at /usr/bin/composer:24

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by mervick** [comment]
Fixed

**Comment by shiquemano** [comment]
Fix confirmed.  Thanks!
