### ISSUE TITLE
Support For Dart

### ISSUE THREAD

**Issue by Dennis247** [mervick/aes-everywhere#19]
It will be aawesome if aes-everywhere for **dart** Language is made available. Thank You.

**Comment by vkammerer** [comment]
Looking forward to this too!

**Comment by ikomangmahendra** [comment]
+1 Please implement this soon

**Comment by rmedeiro** [comment]
Estou na esperança tembém, temos alguma previsão para o suporte em dart?

**Comment by mervick** [comment]
Added dart implementation
https://github.com/mervick/aes-everywhere/blob/master/dart/aeseverywhere/lib/aeseverywhere.dart
