### ISSUE TITLE
(Python) TypeError: must be str, not bytes: line 89, in __derive_key_and_iv

### ISSUE THREAD

**Issue by atishagrawal** [mervick/aes-everywhere#2]
I am getting this error
```
line 89, in __derive_key_and_iv
    d_i = md5(d_i + password + salt).digest()
TypeError: must be str, not bytes
```

when I am trying to execute the python code

I am using it like this:

`print(aes256.aes256().encrypt("Hello World", "pass"))`

**Comment by mervick** [comment]
python version ?

**Comment by atishagrawal** [comment]
Python 3.6.5

**Comment by mervick** [comment]
Fixed here https://github.com/mervick/aes-everywhere/commit/54638742430ef9eb60664cab793cbaf8bfac98e7
