### ISSUE TITLE
(PHP) Multiple Deprecated Warnings

### ISSUE THREAD

**Issue by atishagrawal** [mervick/aes-everywhere#3]
While executing your PHP Code, I am receiving several deprecated warnings, some of which are:

```
1. Deprecated: Function mcrypt_module_open()
2. Deprecated: Function mcrypt_generic_init()
3. Deprecated: Function mdecrypt_generic()
4. Deprecated: Function mcrypt_generic_deinit()
5. Deprecated: Function mcrypt_module_close()
```

**Comment by mervick** [comment]
it uses `openssl_encrypt`, any reference to `mcrypt` at all

**Comment by atishagrawal** [comment]
I have openssl installed on my system. But then why is the PHP code showing such deprecated warnings?

**Comment by mervick** [comment]
I have no idea why, but this file does not use mcrypt.
Check your code, I think it use that somewhere else.
Also please provide full stack trace with filenames and line numbers.

**Comment by atishagrawal** [comment]
Anyways, no problem bro. I have compiled my own Library
