### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by iridesc** [mervick/aes-everywhere#30]
File "/usr/local/python3/lib/python3.9/site-packages/aes_everywhere-1.2.8-py3.9.egg/AesEverywhere/aes256.py", line 32, in <module>
    from Crypto import Random
ModuleNotFoundError: No module named 'Crypto'

**Comment by iridesc** [comment]
i fix it temportly by install  ```pycryptodomex``` and modified you package by 
replace 

```
from Crypto import Random
from Crypto.Cipher import AES
```
to 
```
from Cryptodome import Random
from Cryptodome.Cipher import AES

```
waiting for you to fix it in the next version!

**Comment by mervick** [comment]
Fixed
