### ISSUE TITLE
c++ AES runtime error

### ISSUE THREAD

**Issue by sleepreading** [mervick/aes-everywhere#33]
#0  0x00002aaaab21d207 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00002aaaab21e8f8 in __GI_abort () at abort.c:90
#2  0x00002aaaab25fd27 in __libc_message (do_abort=2, fmt=fmt@entry=0x2aaaab371678 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#3  0x00002aaaab267d97 in malloc_printerr (ar_ptr=0x2aaaab5ad760 <main_arena>, ptr=0x45e360, str=0x2aaaab36ecf7 "corrupted size vs. prev_size", action=<optimized out>) at malloc.c:5004
#4  malloc_consolidate (av=av@entry=0x2aaaab5ad760 <main_arena>) at malloc.c:4161
#5  0x00002aaaab26967b in _int_malloc (av=av@entry=0x2aaaab5ad760 <main_arena>, bytes=bytes@entry=16) at malloc.c:3791
#6  0x00002aaaab26c1ac in __GI___libc_malloc (bytes=16) at malloc.c:2905
#7  0x000000000040380a in Pkcs7Padding(unsigned char*, unsigned int) ()
#8  0x0000000000403b16 in AES256::encrypt(unsigned char const*, unsigned long, unsigned char const*) ()

**Comment by mervick** [comment]
There is a notice in [README](https://github.com/mervick/aes-everywhere/blob/master/cpp/README.md).
C++ version does not work
