### ISSUE TITLE
Security warnings for the node and possibly other packages

### ISSUE THREAD

**Issue by NeoPrint3D** [mervick/aes-everywhere#41]
![image](https://github.com/mervick/aes-everywhere/assets/77029802/c268ec2c-4271-4205-8bbf-c4ff2d4a8ec6)

**Comment by mervick** [comment]
Warnings about dev packages for build using grunt.

**Comment by NeoPrint3D** [comment]
Does that mean the npm package is fixed and updated with the latest dependencies?

**Comment by mervick** [comment]
There is no any outdated dependencies in distribution package. Grunt just build the package
